---
kind: pipeline
name: default
type: docker

steps:
- name: build
  image: plugins/docker
  settings:
    target: builder
    purge: true
    dry_run: true
    repo: reg.infra.riesiner.dev/lecture-mod

- name: publish
  image: plugins/docker
  settings:
    repo: reg.infra.riesinger.dev/lecture-mod
    registry: reg.infra.riesinger.dev
    auto_tag: true
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
  when:
    event: tag

- name: update-service
  image: appropriate/curl
  environment:
    URL:
      from_secret: service_update_url
  commands:
  - curl -X POST $URL
  when:
    event: tag
