pipeline:
  build:
    image: golang:1.10.2-alpine
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    commands:
      - go get -v 
      - go vet -v
      - go build -v -a -installsuffix cgo -o lecture-mod .
  publish-docker:
    image: docker
    secrets: [ docker_username, docker_password ]
    commands:
      - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD registry.pascal-riesinger.de
      - docker build -t registry.pascal-riesinger.de/lecture-mod:latest .
      - docker push registry.pascal-riesinger.de/lecture-mod:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master
      event: push
  rancher-deploy:
    image: peloton/drone-rancher
    url: http://pascal-riesinger.de:8089
    secrets: [ rancher_access_key, rancher_secret_key ]
    service: tools/lecture-mod
    docker_image: registry.pascal-riesinger.de/lecture-mod:latest
    start_first: false
    interval_millis: 5000
    confirm: true
    timeout: 180
    when:
      branch: master
      event: push
  telegram-notify:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
